### ISSUE TITLE
DCM doubt

### ISSUE THREAD

**Issue by gianm96** [pololu/minimu-9-ahrs-arduino#22]
In the Drift_correction() function, when computing the PI feedback controll of the error there's a weighed average of RollPitchError and YawError (as I saw that you referred to a paper discussing DCM applications). The RollPitchError is weighted, but the YawError isn't. Shouldn't it be weighted with something as
> 1 - Accel_weight

? Or maybe you just did a different elaboration?
I'm just curious, I'm studying the DCM applied for AHRS for an Arduino based quadcopter :grinning:

**Comment by kevin-pololu** [comment]
Hi, gianm96.

It looks like I missed your issue when you first opened it. If you are still looking for an explanation, the basic idea should be that the AHRS uses the gyro for relative measurements of orientation changes on a short timescale, and the accelerometer and magnetometer as absolute references to correct for gyro drift over a long timescale.

The accelerometer is used to determine the "down" direction, used as a reference for the roll and pitch axes, by measuring gravitational acceleration. Since the board will also measure inertial acceleration (such as when it is shaken or it is in a vehicle that accelerates), its measurement of the "down" direction is less likely to be accurate when the magnitude of the measured acceleration differs from 1 g, so the AHRS weights the roll and pitch axis correction accordingly. 

The magnetometer is used to determine the "north" direction, used as a reference for the yaw axis. Since inertial acceleration does not affect the reliability of this measurement, it is not weighted according to the magnitude of the acceleration.
