### ISSUE TITLE
If SCL or SDA doesn't connect , main loop routine  stop.

### ISSUE THREAD

**Issue by Chyon** [pololu/minimu-9-ahrs-arduino#7]
Thank you for useful program.　
In this program ,when　SCL　or SDA pin is not connected to Arduino, loop routine doesn't work.
It means, if SCL pin is cut  accidentally, it does not  Serial print wrong data, but it Serial print no data and any other program in loop also  stops.

I want to make loop program work even if SCL and SDA is not connected.
What should I do?

Please give me some advice.

**Comment by kevin-pololu** [comment]
You could try to make the program behave the way you want by detecting when no response has been received from the sensors within a reasonable time instead of waiting forever for the response. The L3G and LSM303 libraries used by the program have some functions that would probably help you do this (`setTimeout()` and `timeoutOccurred()`).

I am going to close this issue because it is not a bug in the program or a feature that we currently expect to add (which is what we use the issue tracker on GitHub for). If you have additional questions, consider posting on the [Pololu forum](http://forum.pololu.com/) or using our other regular support channels at https://www.pololu.com/support.
